### PR TITLE
Week 3 homework

### PR DESCRIPTION
**Pull request by Corgieater**
Greeting, sir!
Please check my homework, thanks a lot.
http://54.86.81.197:3000/attraction/28

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Width of navigator and footer should extend to full width of screen.
2. Layout exceeds screen width in the mobile devices.

未命名-2
未命名-4

**Comment by Corgieater** [comment]
Sorry, sir, I was too focus on other functions:(
Please check it again, thanks.

**Comment by cwpeng** [comment]
Content of navigator and attractions should align left and right with each other in each side in large screen. (>1200px)

未命名-7
未命名-10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Corgieater** [comment]
Thank you really much, sir!

**Pull request merged**
