### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Corgieater**
范家華
http://54.86.81.197:3000/api/attractions?page=1
http://54.86.81.197:3000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95
http://54.86.81.197:3000/api/attraction/22

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should assume attraction data may be changing during the lifetime of our website, so max page is not a constant number. Try to use LIMIT statement in your SQL query to do range selection.

I mean code below should be replaced by better solution:
```
        search = ('SELECT id, name, category, description, address, transport, mrt, latitude, '
                  'longitude, images FROM taipeitrip')
        cursor.execute(search)
        totalAttractions = cursor.fetchall()
        search = 'SELECT COUNT(*) FROM taipeitrip'
        cursor.execute(search)
        totalAttractionLength = cursor.fetchone()
        totalAttractionLength = totalAttractionLength[0]
        totalPage = math.ceil(totalAttractionLength/11)
        # # hard coded but ok, try to fix it in a smart way after job done, I think it can be iterate
        if int(userInputPage) < totalPage-1:
            #total page -1 because we have 58 items / 11 to ceil will be 6 pages,
            #but we start from 0, 0-4
            if int(userInputPage) == 0:
            elif int(userInputPage) == 1:
            elif int(userInputPage) == 2:
            elif int(userInputPage) == 3:
            elif int(userInputPage) == 4:
```

Fix issues, create new commits, and ask me to review again.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but response format of http://54.86.81.197:3000/api/attraction/22 is not correct. check API spec carefully and fix it.

**Comment by Corgieater** [comment]
Thank you for taking time reviewing my homework, sir!

**Review by cwpeng — APPROVED** [review]
OK. Good Job.

**Pull request merged**
